<?php

return [
    'UPLOADS' => [
        'SCREENSHOTS' => 'screenshots/',
        "PANCARDS"    => 'pan_cards/',
        "RENEW_ACCOUNT_IMAGES"=>'renewal_account_images'
    ],
    'ALLOWED_EXTENSIONS' => ['png','jpeg','jpg','pdf','docx','doc','xlsx','xls'],
    'ALLOWED_MIMETYPES' => ['image/png','image/jpeg','application/pdf','application/vnd.openxmlformats-officedocument.wordprocessingml.document','application/msword','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet','application/vnd.ms-excel','text/plain'],
    'Super Admin' => 1,
    'Admin' => 2,
    'Sub Admin' => 3,
    'HR Manager' => 4,
    'Counsellor' => 5,
    'Teachers' => 6,
    'Students' => 7,
    'Parents' => 8,
    'Permissions'=>[
        "User Management -> Users",
        "User Management -> Roles",
        "Client Management -> Clients",
        "Client Management -> Demat Accounts",
        "Client Management -> Client Status",
        "Partner Management -> Freelancer Data",
        "Partner Management -> Freelancer",
        "Partner Management -> Channel Partner Data",
        "Partner Management -> Channel Partner",
        "Analyst Management -> Analyst",
        "Analyst Management -> Monitor data",
        "Analyst Management -> Reports",
        "Analyst Management -> Monitor",
        "Trade Management -> Trade Hold",
        "Trade Management -> Setup",
        "Trade Management -> Trader data",
        "Trade Management -> Trader",
        "Finance Management -> Renew Status",
        "Finance Management -> Accounting",
        "Finance Management -> Bank",
        "Finance Management -> Financial Status",
        "Finance Management -> Reports",
        "Blog Management -> Blog Data",
        "Blog Management -> Blog",
        "Business Management",
        "Document Management -> Data",
        "Document Management -> Pan cards",
        "Document Management -> Screenshots",
        "Document Management -> Images",
        "Keywords",
        "Settings -> User Account Type",
        "Settings -> Client Profession",
        "Settings -> Client broker",
        "Settings -> Bank details",
        "Settings -> Service type",
        "Settings -> Terms and Condition",
    ],
    "LABEL_TYPES"=>[
        "income",
        "expense",
        "transfer",
        "loan"
    ],
    "USERS_TYPE"=>[
        1=>"Partner",
        2=>"Employee",
        3=>"Channel Partner",
        4=>"Freelancer AMS",
        5=>"Freelancer Prime"
    ],
    "INVOICE_TYPE_BY_SUB_HEADING"=>[
        "AMS Fees"=>1,
        "Prime Fees"=>1,
        "Prime Next Fees"=>1,
        "AMS Profit Sharing"=>2,
        "Prime Profit Sharing"=>2,
        "Prime Next Profit Sharing"=>2,
    ]
];

?>
